### ISSUE TITLE
Points à discuter

### ISSUE THREAD

**Issue by B-frost** [ZenkoSan/FrenchTranslation#3]
Voici un résumé des principaux problèmes et points importants que j'ai rencontré en feuilletant la section 'issues' de la traduction anglaise. J'ai mis autant que possible les liens vers les discussions pertinentes pour que vous en fassiez une idée, par contre ça risque d'être une longue lecture si vous tentez de tout lire. Je vais séparer ça en plusieurs postes.

1.Coordination
L'équipe anglo rencontre présentement des problèmes de coordination due à un grand nombre de nouveaux contributeurs. Il faudrait établir un système pour savoir qui travaille sur quoi, quelles lignes sont considérées ok pour le moment et n'ont pas besoin de retouches pour pouvoir mieux cibler ce qu'il reste à faire. Dans notre cas, avoir aussi une idée de la progression de la traduction anglaises pour savoir quelles lignes sont finales et qu'on peut traduire tout de suite.
L'équipe anglo a suggéré d'ajouter des symboles directement aux lignes ( https://github.com/Treeofsavior/EnglishTranslation/issues/540 ) mais cela cause certains problèmes. Je suggère qu'on évite.
Encourager autant que possible la communication entre les contributeurs pour ne pas se piler sur les pieds et répéter le même travail.

Système proposé par Ensata:Personally, I just made my own progress chart to the side and ticked off boxes, and it's not hard to expand it for more users and track all the passes. I even left it online. That only works if someone's managing it, or if everyone is doing it correctly, though. Working in blocks will also make it easier to follow.
(Bifrost: je cherche présentement le lien pour vous donner l'exemple, j'ai vu ce tableau hier mais il est présentement introuvable)

Status de la traduction anglaise:
    https://github.com/Treeofsavior/EnglishTranslation/issues/850
    https://github.com/Treeofsavior/EnglishTranslation/issues/864
    https://github.com/Treeofsavior/EnglishTranslation/issues/858
Le projet à jour, sur google doc pendant la periode de gel:
    https://docs.google.com/spreadsheets/d/1IUDSTR31ve9lQDn373Z5j0uNPNbCno3v9ypu8mE8sj4/edit?pli=1#gid=1564647179

**Comment by B-frost** [comment]
2.Standardisation
L'équipe anglo s'est entendue pour utiliser la grammaire US plutôt que british. Il faudrait voir si il y a une référence française sur laquelle on devrait se baser pour la grammaire, question de consistance.
Certaines traductions, entre autre pour les items et les skills, doivent suivre certaines règles générales pour rester consistantes. Il faudrait se coordonner pour traduire ces fichiers.
Discussion sur les règles de standardisation (je suggère qu'on en établisse pour les différents fichiers à traduire):
        https://github.com/Treeofsavior/EnglishTranslation/issues/731
        https://github.com/Treeofsavior/EnglishTranslation/issues/776
Discussion originale pour le fichier skill:
        https://github.com/Treeofsavior/EnglishTranslation/issues/672
Items:
        https://github.com/Treeofsavior/EnglishTranslation/issues/283

Quelques trucs mineurs que j'ai noté pour ne pas perdre:
    로우 -> Low ->'Basse qualité'
        https://github.com/Treeofsavior/EnglishTranslation/issues/56
    UN Révélateur ou LE Révélateur
          https://github.com/Treeofsavior/EnglishTranslation/issues/527
          Réponse d'IMC:
            Player is one of the many revelators who is on the quest to become THE revelator hehe :wink:
    신수의 날 -> ( https://github.com/Treeofsavior/EnglishTranslation/issues/432 )
        'Day of the Divine Tree'
        Événement important du jeu. La discussion en lien est le débat sur le terme à utiliser pour la traduction. Des points très intéressant ont été emmenés dans cette discussion, notamment par Ensata et Xenobius2501, un membre du projet qui parle lituanien. Entre autre:'Ever since I saw that "Medis Diena" abomination mentioned in game by NPCs it became apparent that we should change it. As it is, it makes no sense whatsoever, since leaving it in nominative case makes it sound like "Tree. Day." with full stop/period between unrelated words.'

Listes de références d'Ensata, en complément et selon moi plus fiable que celles sur le wiki:
    Termes Importants: 
       https://github.com/ensata/TreeOfSavior-en-research/blob/master/Keyword_notes.tsv
    Noms des maps: 
       https://github.com/ensata/TreeOfSavior-en-research/blob/master/mapnames.tsv
       https://github.com/Treeofsavior/EnglishTranslation/issues/860
Ellipses:
      Il existe un caractère pour l'élipse (…) obtenu en tapant Alt+0133
        Justification: As for using the Unicode ellipsis character, this relates to a rendering bug that can occur in printed books and user interfaces — if you write the ellipsis by typing three periods, there is a chance that word wrap will cut the ellipsis in half, so you get one dot on one line, and two on the other. The Unicode character counts as a single character, so that will never happen. In fact, MS Office and LibreOffice's autocorrect silently replaces it for you. Printed books aren't relevant here, but the problem can also occur in Korean and Japanese games that haven't been reprogrammed for the way that English is laid out, or certain rendering methods in general.

**Comment by B-frost** [comment]
3.Conseils d'Ensata
Ensata est un membre de l'équipe anglo avec de l'expérience dans les projets de traduction sur GitHub. Je vous recommande de regarder un peu son travail sur son profil. Voici quelques-une de ses recommandations générales:
Quelques règles de politesse lors des 'pull requests':
      https://github.com/ensata/ToS-en-fork/blob/notes/GitHub_Usage.txt
Guide de style:
      https://github.com/ensata/ToS-en-fork/blob/notes/Style_Guide.txt

4.Traduction vs. Localisation
(Discussion anglo: https://github.com/Treeofsavior/EnglishTranslation/issues/569 )
Le consensus actuel sur le projet anglo est qu'il reste énormément de
travail de traduction et de standardisation à faire(encore plus pour nous)et les fichiers nous donnent peu d'information sur le contexte des lignes. 
Dans ces conditions, il faut éviter de dévier du texte ou de la traduction originale. Le but pour le moment étant de rendre les lignes confortables à la lecture en ne perdant pas d’information, sans se préoccuper de leur contexte.

5.Guide GitHub(basse priorité)
On doit pour le moment composer avec le fait que nous manquons tous d’expérience avec GitHub. Il faudra éventuellement créer un guide spécifique au projet qui couvrirait les fonctions dont les traducteurs auront besoin.

6.Questions légales
Si vous suivez un peu le projet anglais, vous savez que les pull sont présentement gelés le temps de régler quelques questions légales. Entre autre ceci;
Intellectual Property Rights Ownership

Please be aware that the Intellectual Property Rights of the following, including, but not limited to, belong to IMC Games Co., Ltd: The names of any characters, NPCs, places, scenes, things, events, short phrases, short sayings and the likes that are set forth in Tree of Savior, as well as any translations or contributions from our contributors.

```
                          ⓒ IMCGAMES CO., LTD. All Rights Reserved.
```

a été ajouté récemment au projet GitHub suites au commentaires de certains contributeurs(voir aussi la notice du 11/08/15 ici: https://github.com/Treeofsavior/EnglishTranslation
Je ne veux pas trop m'avancer sur la question légale, je ne m'y connais pas du tout, mais il faut s'attendre à ce que la question se pose éventuellement, et que tout le monde soit au courant le moment venu pour ne pas avoir de mauvaises surprises.

Voila pour les choses principales à savoir, à discuter entre nous. Perso je vais me mettre à travailler sur un système de coordination.

**Comment by NagisaOkazaki** [comment]
Très bon résumé. Merci pour ce travail.

Cela dit, j'aimerai revoir quelque point énoncés par tes soins.
Je suis tout à fait d'accord pour éviter les symboles, cela donne juste un mal au crâne de devoir faire référence aux symboles pour les choses traduites et non-traduites ou en attente de vérification. 
Ayant Discord comme lieu de rendez-vous et de point de communication, il est préférable de rester sur une base stable et sans prise de tête. 
Je pense que si on devrait commencer à utiliser des symboles, ceux-ci devraient être plus communicatif qu'une simple croix.

Ensuite, il faut se mettre d'accord une référence en particulier pour éviter les décalages, c'est un fait, mais laquelle prendre? Je suis loin d'être expert dans ce domaine. 
Je serai plus d'avis d'utiliser des mots simples avec peu de majuscules pour tout ce qui est de la traduction d'"Attribut" ou de certains "Skill". Pareil pour les endroits du monde de ToS.
Après pour les traductions qui proviennent du Lituanien, il ne reste qu'à attendre.

J'avais aussi pensé à faire comme eux, faire un sheet google pour la traduction française, reprendre l'ensemble de leurs tableaux puis y ajouter la traduction française dans des colonnes et lignes supplémentaires. Pour avoir plus de facilité dans le futur pour les traductions.

Pour finir, je pense que nous serons très peu sur le projet de traduction française (j'espère me tromper), j'ai cru comprendre que sur le site de http://www.tree-of-savior.fr/ , ils étaient aussi entrain de bosser sur la traduction (à quel nombre, ça je ne sais pas), il faudra mettre en place des administrateurs qui pourront gérer chacun des domaines de traduction et un administrateur général pour superviser l'ensemble des traductions.
Le plus important sera de rester organisé et de ne pas dévier de nos "règles" principales.

**Comment by B-frost** [comment]
Intéressant, j'avais seulement regardé rapidement les fansites français en me disant qu'une fois qu'on aurait une bonne base on pourrait rassembler les gens intéressés pour la traduction. Je vais essayer de voir où ils en sont pour le moment.

**Comment by B-frost** [comment]
Je laisse ici un lien pour le serveur Discord: https://discord.gg/0SZXZzm4YXvpZPwr

**Comment by ZenkoSan** [comment]
Merci pour toutes ces précieuses informations récoltées,

J'ai lu les différents guides d'Ensata ainsi qu'une bonne partie des débats sur la standardisation de l'écriture et on est vite dépassé par la liste de choses qu'il reste à clarifier et l'introduction de mots lituaniens dans certains noms de zones et d'objets ne fait que compliquer le tout et le rendre encore plus confus.
Je ne pense pas que nous puissions définir nos propres règles sur ces sujets, de plus actuellement IMCgames prend part aux débats et éclaire les points d'obscurité (en tout cas ils y prenaient part avant cette "pause"). Leurs débats sont intéressants mais ils masquent un peu les solutions dégagées si bien qu'après avoir lu toutes ces discussions je ne sais finalement pas ce qui a été décidé de manière définitive. Je suppose qu'un point de clarification s'imposera, un résumé je l'espère.

Pour ce qui sera de nos propres règles elles traiteront surtout de l'organisation de notre travail. 
Concernant le reste je crains que nous ne puissions qu'attendre de voir les choix définitifs qui seront faits.

**Comment by ZenkoSan** [comment]
Je clos cette issue de manière à ce que les références et le travail de B-frost restent facilement accessibles. (Elle restera visible pas d'inquiétude)

Si vous avez des suggestions, des idées ou des avis à donner concernant l'organisation du travail dans l'équipe faites-le dans un nouveau sujet s'il n'y en a pas déjà un :)
