### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by moutonnoireu** [ZenkoSan/FrenchTranslation#4]
Sur cette page https://github.com/ZenkoSan/FrenchTranslation/wiki/2.1.-Classes, il manque tous les accents (ou du moins une bonne partie, Télékinésiste, etc). Est-ce un choix ?

**Comment by zordagoth** [comment]
Non du tout, juste une flemme j'imagine :p 

Etant donné que certaines traductions KR>EN sont plus que douteuse, on est loin d'avoir fignolé les détails =)

**Comment by ZenkoSan** [comment]
Pour les accents il n'y a pas encore de décision définitive du coup parfois il y en a et d'autres fois non. Nous ne savons pas comment est conçu le jeu en ce qui concerne l'encodage des caractères étant donné que pour l'instant ni l'anglais et encore moins le coréen n'en disposent.

**Comment by zordagoth** [comment]
En même temps des accents en anglais c'est plutôt rare :P

**Comment by ZenkoSan** [comment]
Ils auraient pû décider de conserver les accents des mots de lituanien :)
